### ISSUE TITLE
Discuss Themes

### ISSUE THREAD

**Issue by mjbrender** [evangelistcollective/evangelistcollective.github.io#1]
Design deserves discussion. 

There are great Jekyll layouts [curated here](http://jekyllthemes.org). I'm starting with [Freelancer](http://jekyllthemes.org/themes/freelancer/) for now, though I'd love for others to weigh in on style going forward. 

Nothing urgent here - I just want others to know what we have available to us.

**Comment by djosephsen** [comment]
I'm neither adept at web design, nor strongly opinionated about it, but I think Freelancer is way better than what I would have chosen heh.

**Comment by mjbrender** [comment]
We're happy with where this is at for now.
