### ISSUE TITLE
Rebranding: Changing text in our logo

### ISSUE THREAD

**Issue by jerdog** [evangelistcollective/evangelistcollective.github.io#12]
As mentioned in https://github.com/evangelistcollective/getting-started/issues/15 we'll need to adjust text in our logo from ""The Evangelist Collective" to "DevRel Avocados", err I mean "The DevRel Collective"

**Comment by jerdog** [comment]
Anyone have the original (hopefully with layers still intact)?

**Comment by mbbroberg** [comment]
Negative on having the original. I did build a new one here https://github.com/deverelcollective/brand
