### ISSUE TITLE
Update Locations

### ISSUE THREAD

**Issue by mjbrender** [evangelistcollective/evangelistcollective.github.io#5]
Who lives where? Who wants to be listed here? Here's what I put in so far and it's defined in `_config.yml`.

![screen shot 2015-05-30 at 2 48 34 pm](https://cloud.githubusercontent.com/assets/1744971/7898833/fa56cbde-06da-11e5-88d1-ee282fdd0d5d.png)

**Comment by djosephsen** [comment]
I fixed my location and added florian.  I think that's all correct now

**Comment by mjbrender** [comment]
Florian is in Boston?! I need to catch up with him @djosephsen. 

Also, resolving this one. Thanks :+1:
